### ISSUE TITLE
Textbox content is not saved under some circumstances

### ISSUE THREAD

**Issue by mwigham** [polifonia-project/dashboard#57]
If I add a textbox and fill in text, then click on Save, then my textbox content is not saved.

If I add a textbox and fill in text, then click outside the textbox, then click on Save, then the content is saved

If I add a textbox and fill in text, then click on Save twice, then the content is saved

**Comment by mondoboia** [comment]
This issue is resolved by the introduction of the text editor ( #48 ).

**Comment by mondoboia** [comment]
Problem overcome by the text editor behavior.
